backend:
  name: github
  repo: newjersey/innovation.nj.gov
  api_root: https://api.github.com
  base_url: https://z2o7ybyt5b.execute-api.us-east-1.amazonaws.com
  auth_endpoint: auth
  publish_mode: editorial_workflow
  squash_merges: true
media_folder: assets/images
public_folder: /assets/images

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "content/_blog/"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    create: true
    summary: '{{title}} ({{date | date("MM/DD/YYYY")}}): "{{body | truncate(80, "...")}}"'
    fields:
      # Read-only fields
      - name: layout
        label: Layout
        widget: hidden
        default: blog
      # Required fields
      - name: title
        label: Title
        widget: string
        required: true
      - name: author
        label: Author
        widget: string
        required: true
      - name: date
        label: Publish Date
        widget: datetime
        date_format: true
        default: { { now } }
        required: true
      # Optional fields
      - name: excerpt
        label: Excerpt
        widget: string
        hint: Optional text either summarizing the content or quoting it. Used to display the article in a list as a preview.
      - name: image
        label: Featured Image
        widget: image
        media_folder: "assets/images"
        allow_multiple: false
        choose_url: false
        required: false
      - name: promoted
        label: Promoted Order
        hint: There is only 1 promoted blog post at a time. \"0\" values (the default) are unpromoted.
        widget: number
        value_type: "int"
        default: 0
        min: 0
        max: 1
        required: true
      - name: figure
        label: Inline Image
        hint: Embed this image by inserting the following text "{% include figure.html %}" somewhere in the body of content.
        widget: object
        required: false
        fields:
          - name: url
            label: Image
            widget: image
            media_folder: "assets/images"
            allow_multiple: false
            choose_url: false
            required: false
          - name: caption
            label: Image Caption
            widget: string
            required: false
          - name: alt-text
            label: Image "alt" text
            widget: string
            required: false
      - name: body
        label: Body
        required: true
        widget: markdown
  - name: "news"
    label: "News Posts"
    folder: "content/_news/"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    summary: '{{title}} ({{date | date("MM/DD/YYYY")}}): "{{body | truncate(80, "...")}}"'
    create: true
    fields:
      # Required fields
      - name: title
        label: Title
        widget: string
        required: true
      - name: date
        label: Publish Date
        hint: This should be the date the referenced article was published
        widget: datetime
        date_format: true
        default: { { now } }
        required: true
      - name: source
        label: Source
        hint: e.g. the name of the site/org/dept that published the article
        widget: string
        required: true
      - name: image
        label: Icon Image
        widget: image
        media_folder: "assets/images"
        allow_multiple: false
        choose_url: false
        required: true
      - name: promoted
        label: Promoted Order
        hint: You can have up to 3 promoted posts in total. \"0\" values (the default) are unpromoted.
        widget: number
        value_type: "int"
        default: 0
        min: 0
        max: 3
        required: true
      - name: body
        label: Description
        hint: A brief description of the article's content.
        required: true
        widget: markdown
      - name: cta
        label: Article Link
        widget: object
        required: true
        fields:
          - name: link
            label: Url
            widget: string
          - name: text
            label: Button Text
            default: Continue Reading
            widget: string
