backend:
  name: github
  repo: newjersey/innovation.nj.gov
  branch: jviall/decap-cms # Branch to update (optional; defaults to master)
  api_root: https://api.github.com
  base_url: https://z2o7ybyt5b.execute-api.us-east-1.amazonaws.com
  auth_endpoint: auth
media_folder: "assets/uploads"
collections:
  - name: "blog"
    label: "Blog"
    folder: "_blog/"
    fields:
      - { name: title, label: Title, widget: string }
      - { name: author, label: Author, widget: string }
      - { name: content, label: Content, widget: markdown }
      - { name: layout, label: Layout, widget: hidden, default: blog }
