name: Redeploy AWS Amplify

on:
  schedule:
    - cron: "0 14 * * *" # 10 AM ET (2 PM UTC)
    - cron: "0 21 * * *" # 5 PM ET (9 PM UTC)
  workflow_dispatch:

jobs:
  redeploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Amplify Redeploy via Webhook
        run: |
          curl -X POST ${{ secrets.AMPLIFY_WEBHOOK_URL }}
